"""mortgage documents

Revision ID: 68dff64bc280
Revises: e28b6f66b59f
Create Date: 2026-10-02 05:10:43.871077

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '68dff64bc280'
down_revision = 'e28b6f66b59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mortgage_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mortgage_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mortgage_id'], ['mortgage.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mortgage_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mortgage_document_mortgage_id'), ['mortgage_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mortgage_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mortgage_document_mortgage_id'))

    op.drop_table('mortgage_document')
    # ### end Alembic commands ###
