"""initial schema

Revision ID: b33d016bc6db
Revises: 
Create Date: 2026-10-02 02:46:47.027369

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b33d016bc6db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(length=60), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series', 'date', name='uq_series_date')
    )
    with op.batch_alter_table('market_observation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_observation_series'), ['series'], unique=False)

    op.create_table('mortgage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('borrower_name', sa.String(length=200), nullable=False),
    sa.Column('borrower_email', sa.String(length=200), nullable=True),
    sa.Column('borrower_phone', sa.String(length=50), nullable=True),
    sa.Column('guarantors', sa.String(length=300), nullable=True),
    sa.Column('property_address', sa.String(length=300), nullable=False),
    sa.Column('property_city', sa.String(length=100), nullable=True),
    sa.Column('property_province', sa.String(length=50), nullable=True),
    sa.Column('property_type', sa.String(length=30), nullable=True),
    sa.Column('property_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('appraisal_date', sa.Date(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('prior_charges', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pin', sa.String(length=50), nullable=True),
    sa.Column('principal_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('rate_type', sa.String(length=20), nullable=True),
    sa.Column('prime_spread', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('rate_floor', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('compounding', sa.String(length=20), nullable=True),
    sa.Column('payment_type', sa.String(length=20), nullable=True),
    sa.Column('payment_frequency', sa.String(length=20), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amortization_months', sa.Integer(), nullable=True),
    sa.Column('funded_date', sa.Date(), nullable=False),
    sa.Column('first_payment_date', sa.Date(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('ownership_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('lender_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('broker_name', sa.String(length=200), nullable=True),
    sa.Column('broker_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lawyer_name', sa.String(length=200), nullable=True),
    sa.Column('renewal_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('nsf_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('prepayment_terms', sa.String(length=300), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('property_tax_status', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('match_keywords', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('news_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=1000), nullable=False),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_table('setting',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('statement_import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('duplicate_count', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('password_stamp', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.String(length=1000), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('bank_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statement_import.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_transaction_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transaction_statement_id'), ['statement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transaction_status'), ['status'], unique=False)

    op.create_table('pending_upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('mortgage_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mortgage_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('principal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fees', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('bank_transaction_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transaction.id'], ),
    sa.ForeignKeyConstraint(['mortgage_id'], ['mortgage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mortgage_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mortgage_transaction_bank_transaction_id'), ['bank_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mortgage_transaction_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_mortgage_transaction_mortgage_id'), ['mortgage_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mortgage_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mortgage_transaction_mortgage_id'))
        batch_op.drop_index(batch_op.f('ix_mortgage_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_mortgage_transaction_bank_transaction_id'))

    op.drop_table('mortgage_transaction')
    op.drop_table('pending_upload')
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_transaction_status'))
        batch_op.drop_index(batch_op.f('ix_bank_transaction_statement_id'))
        batch_op.drop_index(batch_op.f('ix_bank_transaction_date'))

    op.drop_table('bank_transaction')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    op.drop_table('user')
    op.drop_table('statement_import')
    op.drop_table('setting')
    op.drop_table('news_item')
    op.drop_table('mortgage')
    with op.batch_alter_table('market_observation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_observation_series'))

    op.drop_table('market_observation')
    # ### end Alembic commands ###
