"""per-user mortgage form fields

Revision ID: df3e9e3e4414
Revises: e91cd64b12bd
Create Date: 2026-10-04 12:43:12.083514

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'df3e9e3e4414'
down_revision = 'e91cd64b12bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_fields', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('form_fields')

    # ### end Alembic commands ###
