"""term history for renewals

Revision ID: e28b6f66b59f
Revises: b33d016bc6db
Create Date: 2026-10-02 02:51:57.628797

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e28b6f66b59f'
down_revision = 'b33d016bc6db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mortgage_id', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('rate_type', sa.String(length=20), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('prime_spread', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('rate_floor', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('compounding', sa.String(length=20), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amortization_months', sa.Integer(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mortgage_id'], ['mortgage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('term_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_term_history_mortgage_id'), ['mortgage_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('term_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_term_history_mortgage_id'))

    op.drop_table('term_history')
    # ### end Alembic commands ###
