"""mortgage activity log

Revision ID: e91cd64b12bd
Revises: 68dff64bc280
Create Date: 2026-10-02 05:12:49.543819

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e91cd64b12bd'
down_revision = '68dff64bc280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mortgage_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mortgage_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('follow_up_on', sa.Date(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mortgage_id'], ['mortgage.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mortgage_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mortgage_activity_follow_up_on'), ['follow_up_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_mortgage_activity_mortgage_id'), ['mortgage_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mortgage_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mortgage_activity_mortgage_id'))
        batch_op.drop_index(batch_op.f('ix_mortgage_activity_follow_up_on'))

    op.drop_table('mortgage_activity')
    # ### end Alembic commands ###
